card_badge_security:
  template: card_badge
  triggers_update:
    - "[[[ return variables.doors_entities ]]]"
    - "[[[ return variables.motions_entities ]]]"
  label: >
    [[[
      if (variables.doors_entities && states[variables.doors_entities].state != '0') {
        if(states[variables.doors_entities].state == '1') {
          return "door open";
        }
        else {
          return "doors open";
        }
      }
      else if (variables.motions_entities && states[variables.motions_entities].state != '0') {
        if(states[variables.motions_entities].state == '1') {
          return "room with activity";
        }
        else {
          return "rooms with activity";
        }
      }
      else {
        return "Activity";
      }
    ]]]
  name: >
    [[[
      if (variables.doors_entities && states[variables.doors_entities].state != '0') {
        if(states[variables.doors_entities].state == '1') {
          return "1";
        }
        else {
          return states[variables.doors_entities].state;
        }
      }
      else if (variables.motions_entities && states[variables.motions_entities].state != '0') {
        if(states[variables.motions_entities].state == '1') {
          return "1";
        }
        else {
          return states[variables.motions_entities].state;
        }
      }
      else {
        return "No";
      }
    ]]]
  icon: |
    [[[
      if (variables.doors_entities && states[variables.doors_entities].state != '0') {
        return "mdi:door-open";
      }
      else if (variables.motions_entities && states[variables.motions_entities].state != '0') {
        return "mdi:motion-sensor";
      }
      else {
        return "mdi:sleep";
      }
    ]]]
  styles:
    card:
      - background-color: >
          [[[
            if (variables.doors_entities && states[variables.doors_entities].state != '0') {
              return "var(--red)";
            }
            else if (variables.motions_entities && states[variables.motions_entities].state != '0') {
              return "var(--orange)";
            }
            else {
              return "var(--contrast20)";
            }
          ]]]
    name:
      - color: >
          [[[
            if ((variables.doors_entities && states[variables.doors_entities].state != '0') ||
                (variables.motions_entities && states[variables.motions_entities].state != '0')) {
              return 'var(--black)';
            }
            else {
              return 'var(--contrast1)';
            }
          ]]]
    label:
      - color: >
          [[[
            if ((variables.doors_entities && states[variables.doors_entities].state != '0') ||
                (variables.motions_entities && states[variables.motions_entities].state != '0')) {
              return 'var(--black)';
            }
            else {
              return 'var(--contrast12)';
            }
          ]]]
    icon:
      - color: |
          [[[
            if ((variables.doors_entities && states[variables.doors_entities].state != '0') ||
                (variables.motions_entities && states[variables.motions_entities].state != '0')) {
              return 'var(--black)';
            }
            else {
              return 'var(--contrast1)';
            }
          ]]]
